name: C++ Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build Program
      run: g++ Hello_world.cpp -o hello

    - name: Run Tests
      run: |
        chmod +x Hello_world_test.sh
        ./Hello_world_test.sh
        name: C++ Build CI + Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    #job 1
    build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Run Tests
      run: |
        chmod +x Hello_world_test.sh
        ./Hello_world_test.sh

    # wrote it as another job
    #job 2
    docker-build-and-push:  
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker login to Docker Hub
      run: |
        docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

    - name: Build Docker image
      run: |
        docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/hello-ci:latest" .

    - name: Push Docker image to Docker Hub
      run: |
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/hello-ci:latest"
